FROM mysql:latest

ENV MYSQL_ROOT_PASSWORD=${MYSQL_ROOT_PASSWORD}
ENV MYSQL_DATABASE=suitecrm
ENV MYSQL_USER=suitecrm
ENV MYSQL_PASSWORD=${MYSQL_SUITECRM_PASSWORD}

WORKDIR /usr/src/app

EXPOSE 3306


CMD ["mysqld"]
